version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    ports:
            - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/ --auto-reload
    volumes:
            - ./logstash/config:/etc/logstash/conf.d:z
    ports:
            - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
            - ./kibana/config/:/opt/kibana/config/:z
    ports:
            - "127.0.0.1:5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

networks:
  docker_elk:
    driver: bridge
